chore: move PR creation to separate job

diff --git a/.github/workflows/checkout-commit-push.yml b/.github/workflows/checkout-commit-push.yml
--- a/.github/workflows/checkout-commit-push.yml
+++ b/.github/workflows/checkout-commit-push.yml
@@ -24,7 +24,7 @@ jobs:
           git config user.email 'github-actions[bot]@users.noreply.github.com'
           git add reports/
           git commit -m "$message"
-          git push
+          # git push
       
       - name: Create a PR
         id: pr-create
@@ -35,24 +35,31 @@ jobs:
 
           if [[ -n "$pull_request_url" ]]; then
             echo "pull_request_url=$pull_request_url" >> "$GITHUB_OUTPUT"
-            echo 'job_status_emoji=":tails-success:"' >> "$GITHUB_OUTPUT"
             exit 0
           fi
-          echo 'job_status_emoji=":tails-sad:"' >> "$GITHUB_OUTPUT"
           exit 1
-          
+
+  notify-slack:
+    if: ${{ always() }}
+    needs: checkout-commit-push
+    runs-on: ubuntu-latest
+    steps:
+      - name: Adjust the env variables
+        id: adjust-env-vars
+        run: |
+          echo "job_status_emoji=$([[ jobs.checkout-commit-push.result == \"failure\" ]] && echo \":tails-success:\" || echo \":tails-sad:\")" >> "$GITHUB_OUTPUT"
+
       - name: Send GitHub Action trigger data to Slack workflow
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         id: slack
-        if: ${{ always() }}
         uses: slackapi/slack-github-action@v1.23.0
         with:
           payload: |
             {
-              "job_status": "${{ job.status }}",
-              "job_status_emoji": "${{ steps.pr-create.outputs.job_status_emoji }}",
+              "job_status": "${{ jobs.checkout-commit-push.result }}",
+              "job_status_emoji": "${{ steps.adjust-env-vars.outputs.job_status_emoji }}",
               "job_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
-              "pull_request_url": "${{ steps.pr-create.outputs.pull_request_url }}",
+              "pull_request_url": "${{ needs.checkout-commit-push.outputs.pull_request_url }}",
               "commit_url": "${{ github.event.head_commit.url }}"
             }
